### ISSUE TITLE
Failing to parse with current data file

### ISSUE THREAD

**Issue by ghost** [udger/udger-ruby#1]
This is almost certainly a data issue, but I'm posting it here because the bad data is raising an error in the gem.

Output from udger-updater.sh (license key redacted, but we're licensed):

SUBSCRIPTION_KEY: ********
DOWNLOAD_DIR: .
DATA_FILE: udgerdb_v3.dat
DATA_FILE_SHA1: udgerdb_v3_dat.sha1
VERSION_FILE: ./version
VERSION_FILE_TMP: ./version.tmp

Base URL: https://data.udger.com/********
Updating via CURL
No previous version found, start download
Checksum ok
Data downloaded sucesfully: udgerdb_v3.dat
Current version is 20180401-01

Result of calling Udger::Parser.new(Rails.root.join('tmp', 'udger')).parse_ua(string) with a valid string:

Unexpected error #<RegexpError: unmatched close parenthesis: /^Mozilla.*Android.*novoCrystal) Build/i>

/usr/local/bundle/gems/udger-0.1.0/lib/udger/base_parser.rb:14:in `initialize'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/base_parser.rb:14:in `new'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/base_parser.rb:14:in `regexp'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/base_parser.rb:19:in `block in regexp_parse'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:145:in `block (2 levels) in execute'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:110:in `block in each'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:143:in `block in execute'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/usr/local/bundle/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/base_parser.rb:18:in `regexp_parse'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/ua_parser.rb:160:in `parse_device'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/ua_parser.rb:34:in `parse'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/parser.rb:52:in `parse_ua_no_cache'
/usr/local/bundle/gems/udger-0.1.0/lib/udger/parser.rb:26:in `parse_ua'

**Comment by mensfeld** [comment]
@ffmike works fine for me.
